version: '3'

services:
  db:
    image: postgres
  crawler:
    build: .
    image: crawler-image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - selenium
    depends_on:
      - db
  migration:
    image: crawler-image
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
